// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Infrastructure.Data;

#nullable disable

namespace Tracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260818110057_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Tracker.Domain.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("InterviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobBoard")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("JobUrl")
                        .IsUnique();

                    b.HasIndex("PostedDate");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Models.Job", b =>
                {
                    b.OwnsOne("Tracker.Domain.Models.JobAnalysis", "Analysis", b1 =>
                        {
                            b1.Property<long>("JobId");

                            b1.PrimitiveCollection<string>("MatchingStrengths")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("MissingKeywords")
                                .IsRequired();

                            b1.Property<string>("Reason")
                                .IsRequired();

                            b1.Property<string>("SponsorshipNote")
                                .IsRequired();

                            b1.Property<string>("TailoredSummary")
                                .IsRequired();

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1
                                .ToJson("Analysis")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Analysis")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
